Update deploy_scraper.yml

diff --git a/.github/workflows/deploy_scraper.yml b/.github/workflows/deploy_scraper.yml
--- a/.github/workflows/deploy_scraper.yml
+++ b/.github/workflows/deploy_scraper.yml
@@ -55,6 +55,19 @@ jobs:
           docker build -t scraper-lambda -f main_scraper/dockerfile .
           docker tag scraper-lambda:latest $IMAGE
           docker push $IMAGE
+
+          docker run --rm $IMAGE bash -lc "\
+          echo '→ Chrome:' \$((/usr/local/bin/chrome-linux64/chrome --version) 2>&1); \
+          echo '→ Driver:' \$((/usr/local/bin/chromedriver --version) 2>&1)"
+          docker run --rm $IMAGE bash -lc "\
+            ldd /usr/local/bin/chrome-linux64/chrome | grep 'not found' || echo 'Chrome all libs OK'; \
+            ldd /usr/local/bin/chromedriver | grep 'not found' || echo 'Driver all libs OK'"
+          docker run --rm $IMAGE bash -lc "\
+            /usr/local/bin/chrome-linux64/chrome \
+              --headless=new --no-sandbox --disable-setuid-sandbox \
+              --disable-dev-shm-usage --dump-dom https://example.com \
+            || echo 'HEADLESS FAIL';"
+            
       # 6. Update Lambda to use the new image
       - name: Deploy to Lambda
         run: |
